/**
 * Generates responsive derivatives for every source image in public/images.
 *
 * For each source we emit AVIF + WebP + a JPEG fallback at each width in WIDTHS
 * that is not larger than the source itself — upscaling only wastes bytes without
 * adding detail. Output lands in public/images/derived/ as `<name>-<width>.<ext>`,
 * which is gitignored and regenerated by `npm run images` (wired into prebuild),
 * so the repo keeps only the originals.
 *
 * A manifest.json alongside the derivatives records each source's intrinsic size
 * and which widths exist. src/components/Img.tsx reads it to build srcset without
 * hardcoding a per-image list, and scripts/check-images.mjs uses it to detect
 * images being displayed above their native resolution.
 */
import sharp from 'sharp';
import { readdir, mkdir, writeFile, stat } from 'node:fs/promises';
import path from 'node:path';

const SRC_DIR = 'public/images';
const OUT_DIR = 'public/images/derived';
const WIDTHS = [400, 800, 1200, 1600];
const SOURCE_RE = /\.(jpe?g|png|webp)$/i;

// Quality settings tuned for photographic content. AVIF earns a lower number than
// WebP at equivalent perceptual quality, which is most of its size advantage.
const AVIF = { quality: 52, effort: 5 };
const WEBP = { quality: 78 };
const JPEG = { quality: 80, mozjpeg: true, progressive: true };

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const entries = await readdir(SRC_DIR, { withFileTypes: true });
  const sources = entries
    .filter((e) => e.isFile() && SOURCE_RE.test(e.name))
    .map((e) => e.name)
    .sort();

  if (sources.length === 0) {
    console.warn(`No source images found in ${SRC_DIR}`);
    return;
  }

  const manifest = {};
  let written = 0;
  let bytesIn = 0;
  let bytesOut = 0;

  for (const file of sources) {
    const srcPath = path.join(SRC_DIR, file);
    const name = file.replace(SOURCE_RE, '');
    const image = sharp(srcPath, { failOn: 'none' });
    const meta = await image.metadata();
    bytesIn += (await stat(srcPath)).size;

    // Only emit widths the source can actually fill, and always include the
    // source's own width so the largest derivative is a true 1:1 representation.
    const targets = WIDTHS.filter((w) => w <= meta.width);
    if (targets.length === 0 || targets.at(-1) < meta.width) {
      targets.push(Math.min(meta.width, WIDTHS.at(-1)));
    }
    const widths = [...new Set(targets)].sort((a, b) => a - b);

    for (const width of widths) {
      const resized = sharp(srcPath, { failOn: 'none' }).resize({
        width,
        withoutEnlargement: true,
        fit: 'inside',
      });

      const jobs = [
        ['avif', resized.clone().avif(AVIF)],
        ['webp', resized.clone().webp(WEBP)],
        ['jpg', resized.clone().jpeg(JPEG)],
      ];

      for (const [ext, pipeline] of jobs) {
        const outPath = path.join(OUT_DIR, `${name}-${width}.${ext}`);
        const info = await pipeline.toFile(outPath);
        bytesOut += info.size;
        written++;
      }
    }

    manifest[file] = {
      name,
      width: meta.width,
      height: meta.height,
      aspectRatio: +(meta.width / meta.height).toFixed(4),
      widths,
    };

    console.log(
      `  ${file.padEnd(24)} ${String(meta.width).padStart(4)}x${String(meta.height).padEnd(4)}  ->  ${widths.join(', ')}`
    );
  }

  await writeFile(
    path.join(OUT_DIR, 'manifest.json'),
    JSON.stringify(manifest, null, 2) + '\n'
  );

  const mb = (n) => (n / 1024 / 1024).toFixed(2);
  console.log(
    `\n${sources.length} sources -> ${written} derivatives  ` +
      `(originals ${mb(bytesIn)} MB, derivatives ${mb(bytesOut)} MB across all widths/formats)`
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
